products_data = [
    {
        "id": 1,
        "name": "Đèn lồng đỏ truyền thống",
        "price": "150.000",
        "category": "Đèn lồng",
        "image": "https://...",
        "icon": "🏮",
        "stock": 25,
        "status": "active",
    },
    {
        "id": 2,
        "name": "Cành hoa mai vàng",
        "price": "180.000",
        "category": "Hoa mai/đào",
        "image": "https://...",
        "icon": "🌸",
        "stock": 14,
        "status": "active",
    },
    {
        "id": 3,
        "name": "Bao lì xì hoa mai vàng",
        "price": "25.000",
        "category": "Bao lì xì",
        "image": "https://...",
        "icon": "🧧",
        "stock": 120,
        "status": "active",
    },
    {
        "id": 4,
        "name": "Dây treo trang trí Tết",
        "price": "45.000",
        "category": "Dây trang trí",
        "image": "https://...",
        "icon": "🎊",
        "stock": 40,
        "status": "inactive",
    },
]

orders_data = [
    {
        "id": "DH001",
        "customer_name": "Nguyễn Minh Anh",
        "phone": "0901234567",
        "address": "12 Nguyễn Huệ, Q.1, TP.HCM",
        "status": "pending",
        "status_label": "Chờ xác nhận",
        "payment_method": "cod",
        "total_price": 330000,
        "total_price_display": "330.000",
        "created_at": "20/04/2026 09:15",
        "items": [
            {
                "name": "Đèn lồng đỏ truyền thống",
                "quantity": 1,
                "price_display": "150.000",
                "subtotal_display": "150.000",
            },
            {
                "name": "Cành hoa mai vàng",
                "quantity": 1,
                "price_display": "180.000",
                "subtotal_display": "180.000",
            },
        ],
        "note": "Giao giờ hành chính",
    },
    {
        "id": "DH002",
        "customer_name": "Trần Mỹ Linh",
        "phone": "0912345678",
        "address": "88 Lê Lợi, Q.1, TP.HCM",
        "status": "processing",
        "status_label": "Đang xử lý",
        "payment_method": "bank",
        "total_price": 250000,
        "total_price_display": "250.000",
        "created_at": "20/04/2026 10:30",
        "items": [
            {
                "name": "Bao lì xì hoa mai vàng",
                "quantity": 10,
                "price_display": "25.000",
                "subtotal_display": "250.000",
            },
        ],
        "note": "",
    },
    {
        "id": "DH003",
        "customer_name": "Phạm Thu Hà",
        "phone": "0933456789",
        "address": "25 Hai Bà Trưng, Đà Nẵng",
        "status": "shipping",
        "status_label": "Đang giao",
        "payment_method": "cod",
        "total_price": 195000,
        "total_price_display": "195.000",
        "created_at": "19/04/2026 15:20",
        "items": [
            {
                "name": "Dây treo trang trí Tết",
                "quantity": 1,
                "price_display": "45.000",
                "subtotal_display": "45.000",
            },
            {
                "name": "Đèn lồng đỏ truyền thống",
                "quantity": 1,
                "price_display": "150.000",
                "subtotal_display": "150.000",
            },
        ],
        "note": "Gọi trước khi giao",
    },
    {
        "id": "DH004",
        "customer_name": "Võ Thành Đạt",
        "phone": "0988123123",
        "address": "15 Trần Phú, Huế",
        "status": "completed",
        "status_label": "Hoàn thành",
        "payment_method": "bank",
        "total_price": 180000,
        "total_price_display": "180.000",
        "created_at": "18/04/2026 08:45",
        "items": [
            {
                "name": "Cành hoa mai vàng",
                "quantity": 1,
                "price_display": "180.000",
                "subtotal_display": "180.000",
            },
        ],
        "note": "",
    },
    {
        "id": "DH005",
        "customer_name": "Huỳnh Gia Hân",
        "phone": "0977665544",
        "address": "7 Pasteur, TP.HCM",
        "status": "cancelled",
        "status_label": "Đã hủy",
        "payment_method": "cod",
        "total_price": 45000,
        "total_price_display": "45.000",
        "created_at": "17/04/2026 17:00",
        "items": [
            {
                "name": "Dây treo trang trí Tết",
                "quantity": 1,
                "price_display": "45.000",
                "subtotal_display": "45.000",
            },
        ],
        "note": "Khách đổi ý",
    },
]


def build_customers_data():
    customers = [
        {
            "id": 1,
            "code": "KH001",
            "name": "Nguyễn Minh Anh",
            "phone": "0901234567",
            "email": "minhanh@gmail.com",
            "city": "TP.HCM",
            "address": "12 Nguyễn Huệ, Q.1, TP.HCM",
            "order_count": 4,
            "total_spent": 1260000,
            "total_spent_display": "1.260.000",
            "status": "active",
            "status_label": "Đang hoạt động",
            "joined_at": "12/03/2026",
            "note": "",
        },
        {
            "id": 2,
            "code": "KH002",
            "name": "Trần Mỹ Linh",
            "phone": "0912345678",
            "email": "mylinh@gmail.com",
            "city": "Đà Nẵng",
            "address": "88 Lê Lợi, Q. Hải Châu, Đà Nẵng",
            "order_count": 2,
            "total_spent": 580000,
            "total_spent_display": "580.000",
            "status": "active",
            "status_label": "Đang hoạt động",
            "joined_at": "21/03/2026",
            "note": "",
        },
        {
            "id": 3,
            "code": "KH003",
            "name": "Phạm Thu Hà",
            "phone": "0933456789",
            "email": "thuha@gmail.com",
            "city": "Huế",
            "address": "25 Trần Hưng Đạo, Huế",
            "order_count": 1,
            "total_spent": 180000,
            "total_spent_display": "180.000",
            "status": "new",
            "status_label": "Khách mới",
            "joined_at": "01/04/2026",
            "note": "",
        },
        {
            "id": 4,
            "code": "KH004",
            "name": "Võ Thành Đạt",
            "phone": "0988123123",
            "email": "thanhdat@gmail.com",
            "city": "Cần Thơ",
            "address": "15 Hòa Bình, Cần Thơ",
            "order_count": 3,
            "total_spent": 745000,
            "total_spent_display": "745.000",
            "status": "vip",
            "status_label": "VIP",
            "joined_at": "25/02/2026",
            "note": "Thường đặt số lượng lớn",
        },
        {
            "id": 5,
            "code": "KH005",
            "name": "Huỳnh Gia Hân",
            "phone": "0977665544",
            "email": "giahann@gmail.com",
            "city": "TP.HCM",
            "address": "7 Pasteur, TP.HCM",
            "order_count": 1,
            "total_spent": 45000,
            "total_spent_display": "45.000",
            "status": "inactive",
            "status_label": "Tạm khóa",
            "joined_at": "10/04/2026",
            "note": "",
        },
        {
            "id": 6,
            "code": "KH006",
            "name": "Lê Hoàng Nam",
            "phone": "0944556677",
            "email": "hoangnam@gmail.com",
            "city": "Hà Nội",
            "address": "50 Bà Triệu, Hà Nội",
            "order_count": 5,
            "total_spent": 2150000,
            "total_spent_display": "2.150.000",
            "status": "vip",
            "status_label": "VIP",
            "joined_at": "18/02/2026",
            "note": "",
        },
    ]

    for customer in customers:
        parts = customer["name"].strip().split()
        customer["avatar"] = "".join(part[0] for part in parts[:2]).upper()

    return customers


permissions_data = [
    {
        "group_name": "Quản trị viên",
        "members": 1,
        "permissions": [
            "Toàn quyền hệ thống",
            "Quản lý sản phẩm",
            "Quản lý đơn hàng",
            "Quản lý khách hàng",
        ],
    },
    {
        "group_name": "Nhân viên bán hàng",
        "members": 3,
        "permissions": [
            "Xem dashboard",
            "Quản lý đơn hàng",
            "Xem khách hàng",
        ],
    },
    {
        "group_name": "Nhân viên kho",
        "members": 2,
        "permissions": [
            "Xem sản phẩm",
            "Cập nhật tồn kho",
        ],
    },
]